"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$container$all"

[container]
symbol = "ó°¿¦"
style = "red bold"
format = " [$symbol $name]($style)"

[character]
success_symbol = "[ â¯](bold green)"
error_symbol = "[ â¯](bold red)"
vimcmd_symbol = "[ â®](bold green)"
vimcmd_visual_symbol = "[ â®](bold yellow)"
vimcmd_replace_symbol = "[ â®](bold purple)"
vimcmd_replace_one_symbol = "[ â®](bold purple)"

[directory]
format = ' [îš­ $path]($style)[$read_only]($read_only_style) '
style = "bold blue"

[package]
symbol = "ó°“ "
style = 'bold yellow'

[nodejs]
symbol = "ó°‹˜ "

[python]
symbol = "ó°Œ  "

[lua]
symbol = "î˜  "

[git_branch]
symbol = "î©¨ "
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "purple"

[cmake]
symbol = "ó°²‰ "

[golang]
symbol = "î˜§ "

[rust]
symbol = "ó±˜— "

[c]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[bun]
symbol = "ğŸ™ "

[dotnet]
symbol = "ó°ª® "
style = "bold purple"
